export const DEFAULT_SCHEMAS = {
	contacts: {
		properties: {
			Id: { type: "string", title: "ID" },
			Email: { type: "string", title: "Email", format: "email" },
			Title: { type: "string", title: "Title" },
			LastName: { type: "string", title: "Last Name" },
			AccountId: { type: "string", title: "Account ID" },
			FirstName: { type: "string", title: "First Name" },
			Management_Level__c: { type: "string", title: "Management Level" },
			Onemind_Visitor_Id__c: { type: "string", title: "Onemind Visitor ID" },
			Workiva_Created_Lead_Source__c: {
				type: "string",
				title: "Workiva Created Lead Source",
			},
		},
		required: ["Workiva_Created_Lead_Source__c"],
	},
	companies: {
		properties: {
			id: { type: "string", title: "ID" },
			name: { type: "string", title: "Company Name" },
			website: { type: "string", title: "Website", format: "uri" },
			industry: {
				type: "string",
				title: "Industry",
				enum: [
					"Technology",
					"Healthcare",
					"Finance",
					"Manufacturing",
					"Retail",
					"Other",
				],
			},
			size: {
				type: "string",
				title: "Company Size",
				enum: ["1-10", "11-50", "51-200", "201-500", "501-1000", "1000+"],
			},
		},
		required: ["id", "name"],
	},
	tasks: {
		properties: {
			Type: { type: "string", title: "Type" },
			WhoId: { type: "string", title: "Who ID" },
			Status: { type: "string", title: "Status" },
			WhatId: { type: "string", title: "What ID" },
			OwnerId: { type: "string", title: "Owner ID" },
			Subject: { type: "string", title: "Subject" },
			Priority: { type: "string", title: "Priority" },
			Description: { type: "string", title: "Description" },
			ActivityDate: { type: "string", title: "Activity Date", format: "date" },
			RecordTypeId: { type: "string", title: "Record Type ID" },
			AIConversationId: { type: "string", title: "AI Conversation ID" },
		},
		required: ["Type", "Status", "Priority", "Description"],
	},
	leads: {
		properties: {
			Id: { type: "string", title: "ID" },
			FirstName: {
				type: "string",
				title: "First Name",
				mergeStrategy: "overwrite-if-target-empty",
			},
			LastName: {
				type: "string",
				title: "Last Name",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Management_Level__c: {
				type: "string",
				title: "Management Level",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Email: {
				type: "string",
				title: "Email",
				format: "email",
				mergeStrategy: "overwrite-if-target-empty",
			},
			AccountId: {
				type: "string",
				title: "Account ID",
				mergeStrategy: "preserve",
			},
			Title: {
				type: "string",
				title: "Title",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Account_Corporate_Country__c: {
				type: "string",
				title: "Account Corporate Country",
				mergeStrategy: "overwrite-if-target-empty",
			},
			State_Province_Marketo__c: {
				type: "string",
				title: "State Province Marketo",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Last_Touch_Offer__c: {
				type: "string",
				title: "Last Touch Offer",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Last_Touch_Solution__c: {
				type: "string",
				title: "Last Touch Solution",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Contact_Status__c: {
				type: "string",
				title: "Contact Status",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Contact_Owner_Name__c: {
				type: "string",
				title: "Contact Owner Name",
				mergeStrategy: "overwrite-if-target-empty",
			},
			contactProfileFit6sense__c: {
				type: "string",
				title: "Contact Profile Fit 6sense",
				mergeStrategy: "overwrite-if-target-empty",
			},
			account6QA6sense__c: {
				type: "string",
				title: "Account 6QA 6sense",
				mergeStrategy: "overwrite-if-target-empty",
			},
			accountProfileFit6sense__c: {
				type: "string",
				title: "Account Profile Fit 6sense",
				mergeStrategy: "overwrite-if-target-empty",
			},
			accountBuyingStage6sense__c: {
				type: "string",
				title: "Account Buying Stage 6sense",
				mergeStrategy: "overwrite-if-target-empty",
			},
			lead6sense_Segments__c: {
				type: "string",
				title: "Lead 6sense Segments",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Marketo_Id__c: {
				type: "string",
				title: "Marketo ID",
				mergeStrategy: "overwrite-if-target-empty",
			},
			X18_Digit_Id__c: {
				type: "string",
				title: "18 Digit ID",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Account_Owner_Full_Name__c: {
				type: "string",
				title: "Account Owner Full Name",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Pain_Point__c: {
				type: "string",
				title: "Pain Point",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Top_Priority__c: {
				type: "string",
				title: "Top Priority",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Purchase_Timeline__c: {
				type: "string",
				title: "Purchase Timeline",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Status: {
				type: "string",
				title: "Status",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Company: {
				type: "string",
				title: "Company",
				mergeStrategy: "overwrite-if-target-empty",
			},
			OwnerId: {
				type: "string",
				title: "Owner ID",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Account__c: {
				type: "string",
				title: "Account",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Onemind_Visitor_Id__c: {
				type: "string",
				title: "Onemind Visitor ID",
				mergeStrategy: "overwrite-if-target-empty",
			},
			Workiva_Created_Lead_Source__c: {
				type: "string",
				title: "Workiva Created Lead Source",
				mergeStrategy: "overwrite-if-target-empty",
			},
		},
		required: ["Id"],
	},
	AI_Engagement_Conversation__c: {
		properties: {
			Lead__c: { type: "string", title: "Lead" },
			Email__c: { type: "string", title: "Email", format: "email" },
			Title__c: { type: "string", title: "Title" },
			Channel__c: { type: "string", title: "Channel" },
			Contact__c: { type: "string", title: "Contact" },
			Iteration__c: { type: "string", title: "Iteration" },
			Last_Name__c: { type: "string", title: "Last Name" },
			RecordTypeId: { type: "string", title: "Record Type ID" },
			First_Name__c: { type: "string", title: "First Name" },
			Pain_Point__c: { type: "string", title: "Pain Point" },
			Transcript__c: { type: "string", title: "Transcript" },
			Turn_Count__c: { type: "number", title: "Turn Count" },
			Audience_Geo__c: { type: "string", title: "Audience Geo" },
			Channel_Type__c: { type: "string", title: "Channel Type" },
			Top_Priority__c: { type: "string", title: "Top Priority" },
			Calendar_Link__c: { type: "string", title: "Calendar Link" },
			Company_Stage__c: { type: "string", title: "Company Stage" },
			Channel_Format__c: { type: "string", title: "Channel Format" },
			Channel_Vendor__c: { type: "string", title: "Channel Vendor" },
			Audience_Persona__c: { type: "string", title: "Audience Persona" },
			Management_Level__c: { type: "string", title: "Management Level" },
			Audience_Solution__c: { type: "string", title: "Audience Solution" },
			Conversation_Date__c: {
				type: "string",
				title: "Conversation Date",
				format: "date",
			},
			Purchase_Timeline__c: { type: "string", title: "Purchase Timeline" },
			Campaign_Objective__c: { type: "string", title: "Campaign Objective" },
			Onemind_Session_Id__c: { type: "string", title: "Onemind Session ID" },
			Onemind_Visitor_Id__c: { type: "string", title: "Onemind Visitor ID" },
			Solution_Categories__c: { type: "string", title: "Solution Categories" },
			Conversation_Summary__c: {
				type: "string",
				title: "Conversation Summary",
			},
			Key_Topics_Discussed__c: {
				type: "string",
				title: "Key Topics Discussed",
			},
			Calendar_Link_Clicked__c: {
				type: "string",
				title: "Calendar Link Clicked",
			},
			InferredCompanyName6sense__c: {
				type: "string",
				title: "Inferred Company Name 6sense",
			},
		},
		required: [],
	},
} as const;

export type DefaultFormType = keyof typeof DEFAULT_SCHEMAS;
