key: tasks
state: READY
errors: []
isDeactivated: false
id: 682a51d4219c74312f376389
name: Tasks
customized: false
dataSourceKey: tasks
direction: both
defaultImportValue:
  $var: $
defaultExportValue:
  $var: $
